import { PracticeArea, CourtDocket } from '@/types';

export const CHAMBERS_INFO = {
  name: 'Chandra Law Chambers & Dispute Resolution',
  shortName: 'Chandra Law Chambers',
  tagline: 'High-Stakes Commercial Litigation, Domestic & International Arbitration & Sovereign Counsel',
  managingPartner: 'Advocate Shlok Chandra',
  partnerTitle: 'Senior Standing Counsel | Advocate-on-Record Practice',
  barCouncilEnrollment: 'D/1482/2011 (Bar Council of Delhi & Supreme Court Bar Association)',
  experienceYears: 15,
  casesHandled: 2400,
  reportedJudgments: '120+ Reported Precedents',
  offices: [
    'A-22, Ground Floor, Defence Colony, New Delhi – 110024',
    'A-79, First Floor, Defence Colony, New Delhi – 110024',
  ],
  phone: '+91 99996 70588',
  altPhone: '011-47572618',
  email: 'shlokchandra@chandralawchambers.com',
  altEmail: 'admin@chandralawchambers.com',
  workingHours: 'Mon – Sat: 09:30 AM – 08:30 PM',
};

export const PRACTICE_AREAS: PracticeArea[] = [
  {
    id: 'commercial-arbitration',
    name: 'Commercial Arbitration & Section 9/34 Applications',
    slug: 'commercial-arbitration',
    category: 'Arbitration',
    shortDesc: 'Representation in domestic and international institutional arbitrations (DIAC, SIAC, LCIA, ICC) and High Court Section 9/11/34 petitions.',
    fullDesc: 'Led by Shlok Chandra, the arbitration practice handles high-value EPC infrastructure disputes, shareholder joint-venture disagreements, and post-award enforcement under the Arbitration and Conciliation Act, 1996.',
    keyForums: ['Delhi International Arbitration Centre (DIAC)', 'Delhi High Court (Original Jurisdiction)', 'Supreme Court of India'],
    leadCounsel: 'Shlok Chandra, Managing Partner',
    statutoryActs: ['Arbitration and Conciliation Act, 1996', 'Commercial Courts Act, 2015', 'Specific Relief Act'],
    isPrimary: true,
    image: '/assets/courts/arbitration_suite.jpg',
  },
  {
    id: 'high-court-litigation',
    name: 'Constitutional Writs & Delhi High Court Commercial Appeals',
    slug: 'delhi-high-court-litigation',
    category: 'High Court',
    shortDesc: 'Article 226 Constitutional Writ Petitions, Commercial IP Suits, Injunctions, and Company Appeals before the Division Bench.',
    fullDesc: 'Regularly appearing before the Hon’ble Delhi High Court across the original civil side, appellate commercial rosters, and commercial taxation benches.',
    keyForums: ['Hon’ble High Court of Delhi (New Delhi)'],
    leadCounsel: 'Shlok Chandra & Senior Chambers Associates',
    statutoryActs: ['Constitution of India (Art 226/227)', 'Code of Civil Procedure, 1908', 'Commercial Courts Act'],
    isPrimary: true,
    image: '/assets/courts/courtroom_facade.jpg',
  },
  {
    id: 'supreme-court-appeals',
    name: 'Supreme Court Special Leave Petitions (SLPs) & Transfer Petitions',
    slug: 'supreme-court-appeals',
    category: 'Supreme Court',
    shortDesc: 'Strategic drafting and senior advocacy for Article 136 Special Leave Petitions, Civil Appeals, and Contempt Petitions.',
    fullDesc: 'Formulating nuanced constitutional arguments and precedent-setting SLPs before multi-judge constitution benches of the Supreme Court of India.',
    keyForums: ['Supreme Court of India (Tilak Marg, New Delhi)'],
    leadCounsel: 'Shlok Chandra',
    statutoryActs: ['Article 136 of the Constitution', 'Supreme Court Rules, 2013'],
    isPrimary: true,
    image: '/assets/chambers/law_library.jpg',
  },
  {
    id: 'taxation-corporate-defense',
    name: 'Direct Tax Prosecution & NCLAT Corporate Insolvency (IBC)',
    slug: 'taxation-corporate-defense',
    category: 'Taxation & Corporate',
    shortDesc: 'High-stakes Section 260A Income Tax Appeals, corporate debt restructuring (IBC), and white-collar defense.',
    fullDesc: 'Serving as Senior Standing Counsel with unmatched command over complex cross-border transfer pricing, corporate search seizures, and NCLT corporate resolution processes.',
    keyForums: ['Income Tax Appellate Tribunal (ITAT)', 'NCLAT New Delhi', 'High Court Taxation Bench'],
    leadCounsel: 'Shlok Chandra, Senior Standing Counsel',
    statutoryActs: ['Income Tax Act, 1961', 'Insolvency and Bankruptcy Code, 2016 (IBC)'],
    image: '/assets/chambers/defence_colony_office.jpg',
  },
];

export const COURT_DOCKETS: CourtDocket[] = [
  {
    id: 'd-1',
    caseNumber: 'ARB.P. 482/2026',
    matterTitle: 'Vanguard Infra JV vs. National Highways Authority',
    forum: 'Delhi High Court',
    courtRoom: 'Court No. 14 (Commercial Bench)',
    bench: 'Hon’ble Justice Rajiv Shakdher & Hon’ble Justice C. Hari Shankar',
    itemNumber: 7,
    stage: 'Final Arguments',
    hearingDate: '2026-09-02',
    status: 'listed',
  },
  {
    id: 'd-2',
    caseNumber: 'SLP (C) No. 18940/2026',
    matterTitle: 'Apex Energy Ltd. vs. Union of India & Ors.',
    forum: 'Supreme Court of India',
    courtRoom: 'Court No. 3',
    bench: 'Hon’ble Chief Justice Bench',
    itemNumber: 12,
    stage: 'Notice Motion',
    hearingDate: '2026-09-04',
    status: 'listed',
  },
  {
    id: 'd-3',
    caseNumber: 'DIAC Case No. 894/2025',
    matterTitle: 'Singhania Logistics vs. TransGlobal Ports Pvt. Ltd.',
    forum: 'DIAC Arbitration',
    courtRoom: 'Arbitration Suite A, DIAC',
    bench: 'Sole Arbitrator (Former Judge, SC of India)',
    itemNumber: 1,
    stage: 'Cross Examination',
    hearingDate: '2026-09-08',
    status: 'listed',
  },
];
